[DEV-5549] Add total_budgetary_resources to the Budget Category endpoints for total spending
fedspendingtransparency/usaspending-api pull request #2764
Opened 2020-09-03 13:34 UTC by sethstoudenmier

**Description:**
Add `total_budgetary_resources` to the Budget Category endpoints for total spending to support a new "unreported data" line item.

**Technical details:**
Following implementation for DEV-5551 PR, add `total_budgetary_resources` to the Budget Category endpoints to support a new "unreported data" line item for total spending.

**Requirements for PR merge:**

1. [x] Unit & integration tests updated
2. [x] API documentation updated
3. [ ] Necessary PR reviewers:
    - [ ] Backend
4. [x] Matview impact assessment completed
5. [x] Frontend impact assessment completed
6. [x] Data validation completed
7. [x] Appropriate Operations ticket(s) created (N/A)
8. [x] Jira Ticket [DEV-5549](https://federal-spending-transparency.atlassian.net/browse/DEV-5549):
    - [x] Link to this Pull-Request
    - [x] Performance evaluation of affected (API | Script | Download)
    - [x] Before / After data comparison

**Area for explaining above N/A when needed:**
```
```

2020-09-04 22:36 UTC, kwhickey requested changes
Object Class doesn't seem to follow the pattern.

2020-09-04 22:36 UTC, kwhickey commented on usaspending_api/disaster/v2/views/object_class/spending.py
> +            extra_columns = []
Just following the pattern for `federal_account/spending.py` and `agency/spending.py` ... shouldn't this be 
```
extra_columns = ["total_budgetary_resources"]
```
Like those?

2020-09-04 22:39 UTC, kwhickey commented on usaspending_api/disaster/v2/views/object_class/spending.py
> +            extra_columns = []
nvm. Object Class doesn't show budget since GTAS (where budget comes from) doesn't have object class dimensionality.

2020-09-04 22:39 UTC, kwhickey approved these changes

2020-09-05 00:25 UTC, dpb-bah approved these changes

2020-09-05 00:25 UTC, merged