Dev 6505 add agency id to overview
fedspendingtransparency/usaspending-api pull request #2879
Opened 2020-12-21 14:19 UTC by brett-varney

**Description:**
Add agency id to v2/agency/{toptier_code} response

**Technical details:**
Not technical, just adding it

**Requirements for PR merge:**

1. [ ] Unit & integration tests updated
2. [ ] API documentation updated
3. [ ] Necessary PR reviewers:
    - [ ] Backend
    - [ ] Frontend N/A
    - [ ] Operations N/A
    - [ ] Domain Expert N/A
4. [ ] Matview impact assessment completed N/A
5. [ ] Frontend impact assessment completed N/A
6. [ ] Data validation completed
7. [ ] Appropriate Operations ticket(s) created N/A
8. [ ] Jira Ticket [DEV-6505](https://federal-spending-transparency.atlassian.net/browse/DEV-6505):
    - [ ] Link to this Pull-Request
    - [ ] Performance evaluation of affected API N/A
    - [ ] Before / After data comparison

**Area for explaining above N/A when needed:**
Simply adding another column that is already in table

2020-12-21 20:43 UTC, ebdabbs submitted a review, later dismissed
API contract change approved

2020-12-21 20:57 UTC, tony-sappe requested changes

2020-12-21 20:57 UTC, tony-sappe commented on usaspending_api/agency/v2/views/agency_overview.py
> +                "agency_id": self.toptier_agency.toptier_agency_id,
The desired PK is from the `agency` table, not the `toptier_agency` table. 

One API example, which is returning `agency.id` alongside the toptier agency name and code: https://github.com/fedspendingtransparency/usaspending-api/blob/dev/usaspending_api/references/v2/views/toptier_agencies.py#L109

While the above link should be similar enough for this PR, for completely a SQL example which is much more complicated is here: https://github.com/fedspendingtransparency/usaspending-api/blob/dev/usaspending_api/database_scripts/matview_generator/universal_transaction_matview.json#L94

2020-12-23 16:47 UTC, tony-sappe commented on usaspending_api/agency/v2/views/agency_base.py
> +        from usaspending_api.references.models import Agency
While this pattern can reduce imports when this code branch isn't reached, this file is already importing the module on line 17. So for clarity this `Agency` import statement should be combined above

2020-12-23 17:15 UTC, tony-sappe approved these changes

2020-12-23 19:11 UTC, merged