[DEV-6714] Renames usages of agency_code to toptier code in About the Data pages
fedspendingtransparency/usaspending-api pull request #2942
Opened 2021-02-04 16:14 UTC by collinwr

**Description:**
Many usages of `agency_code` in About the Data APIs and documentation actually used the `toptier_code` fields. This PR updates the API endpoints and API documentation to use the correct names.

**Requirements for PR merge:**

1. [x] Unit & integration tests updated
2. [x] API documentation updated
3. [ ] Necessary PR reviewers:
    - [ ] Backend
    - [ ] Frontend <OPTIONAL>
    - [ ] Operations <OPTIONAL>
    - [ ] Domain Expert <OPTIONAL>
4. [ ] Matview impact assessment completed
5. [x] Frontend impact assessment completed
6. [ ] Data validation completed
7. N/A Appropriate Operations ticket(s) created
8. [x] Jira Ticket [DEV-6714](https://federal-spending-transparency.atlassian.net/browse/DEV-6714):
    - [x] Link to this Pull-Request
    - [ ] Performance evaluation of affected (API | Script | Download)
    - [ ] Before / After data comparison

**Area for explaining above N/A when needed:**
```
```

2021-02-04 20:21 UTC, ebdabbs submitted a review, later dismissed

2021-02-05 16:06 UTC, tony-sappe requested changes
Two places in the API contracts were overlooked

2021-02-05 16:06 UTC, tony-sappe commented on usaspending_api/api_contracts/contracts/v2/reporting/agencies/overview.md
>          A data field that will be used to sort the response array.
LN 131

2021-02-05 16:06 UTC, tony-sappe commented on usaspending_api/api_contracts/contracts/v2/reporting/agencies/publish_dates.md
>          + Members
LN 114

2021-02-05 17:34 UTC, collinwr commented on usaspending_api/api_contracts/contracts/v2/reporting/agencies/overview.md
>          A data field that will be used to sort the response array.
Good catch. Fixed

2021-02-05 17:35 UTC, collinwr commented on usaspending_api/api_contracts/contracts/v2/reporting/agencies/publish_dates.md
>          + Members
Good catch. Fixed

2021-02-05 17:44 UTC, tony-sappe approved these changes
Looks good to me. Let's have @ebdabbs review again to coordinate PR merges

2021-02-05 17:56 UTC, ebdabbs approved these changes

2021-02-05 18:07 UTC, merged