[DEV-8643] Add parent_uei to keyword searchs
fedspendingtransparency/usaspending-api pull request #3410
Opened 2022-03-28 15:28 UTC by emily-brents

**Description:**
For whatever reason, the website keyword tooltip lists "parent_uei" as one of the fields that can be searched on for keyword search, even though we never added that field to the list of fields that is searched on with the keyword filter. This PR adds the "parent_uei" field to the keyword filter on advanced search as well as on the keyword search page.

**Technical details:**
Neither the Award ES index or the Transaction ES index had the "parent_uei" field, which might explain why we weren't searching on them.
This PR adds the "parent_uei" field to both indexes, and in the process adds that field to the transaction_search matview, as well as all the `mv_{award_type}_award_search` matviews.

**Requirements for PR merge:**

1. [X] Unit & integration tests updated
2. [X] API documentation updated
3. [ ] Necessary PR reviewers:
    - [ ] Backend
4. [X] Matview impact assessment completed
5. [N/A] Frontend impact assessment completed
6. [X] Data validation completed
7. [ ] Appropriate Operations ticket(s) created
8. [X] Jira Ticket [DEV-8643](https://federal-spending-transparency.atlassian.net/browse/DEV-8643):
    - [X] Link to this Pull-Request
    - [X] Performance evaluation of affected (API | Script | Download)
    - [X] Before / After data comparison

**Area for explaining above N/A when needed:**
```
```

2022-03-29 17:59 UTC, collinwr requested changes
Tested locally, and everything looks good. Just have one question about unit tests below.

2022-03-29 19:17 UTC, emily-brents commented on usaspending_api/search/tests/integration/test_spending_by_transaction.py
> +    assert len(resp.data["results"]) > 0
Well there's only one parent uei in the mock data, so it can only return that one, therefore if it returns anything it counts as a success.

2022-03-29 19:59 UTC, collinwr commented on usaspending_api/search/tests/integration/test_spending_by_transaction.py
> +    assert len(resp.data["results"]) > 0
I'd say better to be explicit here in case test data changes in the future. Can you change this to 1?

2022-03-29 20:07 UTC, emily-brents commented on usaspending_api/search/tests/integration/test_spending_by_transaction.py
> +    assert len(resp.data["results"]) > 0
fine

2022-03-29 21:26 UTC, collinwr submitted a review, later dismissed

2022-03-31 21:56 UTC, sethstoudenmier approved these changes

2022-04-01 14:19 UTC, merged