[PIPE-314] Create summary_state_view as Spark ETL
fedspendingtransparency/usaspending-api pull request #3561
Opened 2022-08-26 17:10 UTC by sethstoudenmier

**Description:**
Implemented the `summary_state_view` matview SQL as a Spark query.

**Technical details:**
Copied over and made minor changes to support the current `summary_state_view` matview SQL as Spark SQL.

**Requirements for PR merge:**

1. [x] Unit & integration tests updated
2. [x] API documentation updated
3. [ ] Necessary PR reviewers:
    - [ ] Backend
4. [x] Matview impact assessment completed
5. [x] Frontend impact assessment completed
6. [x] Data validation completed
7. [x] Appropriate Operations ticket(s) created
8. [x] Jira Ticket [PIPE-314](https://federal-spending-transparency.atlassian.net/browse/PIPE-314):
    - [x] Link to this Pull-Request
    - [x] Performance evaluation of affected (API | Script | Download)
    - [x] Before / After data comparison

**Area for explaining above N/A when needed:**
```
```

2022-08-29 14:01 UTC, kwhickey requested changes
A few questions before final approval.

2022-08-29 14:47 UTC, sethstoudenmier commented on usaspending_api/transactions/delta_models/summary_state_view.py
> +         raw.transaction_fabs ON (transaction_normalized.id = transaction_fabs.transaction_id)
Will make this change once I go to update the PR following merge of other PRs.

2022-08-29 14:49 UTC, sethstoudenmier commented on usaspending_api/transactions/delta_models/summary_state_view.py
> +        ) AS duh,
It is the current way used to create the `duh` value. Not the biggest fan of it, but it is consistent with current implementation.

2022-08-29 16:34 UTC, kwhickey commented on usaspending_api/transactions/delta_models/summary_state_view.py
> +        ) AS duh,
Ok. Can you put a TODO comment inline the sql suggesting a better way to do this key as a future improvement. if e.g. you think the agg_key approach would work.

2022-08-30 15:05 UTC, sethstoudenmier commented on usaspending_api/transactions/delta_models/summary_state_view.py
> +        ) AS duh,
Added a comment

2022-08-30 15:45 UTC, kwhickey approved these changes
Good and clean! Approving.

2022-08-30 15:53 UTC, merged