[DEV-11608] - Add county FIPS code to location autocomplete
fedspendingtransparency/usaspending-api pull request #4219
Opened 2024-11-06 19:10 UTC by zachflanders-frb

**Description:**
From JIRA: 
> The frontend has a list of counties that contains both the FIPS and county name. Currently we provide the county name in the /api/v2/autocomplete/location endpoint, but this can be problematic in the case of either bad data or if the frontend list uses a different name. To help with some of the bad data we should provide the FIPS (five digit code) in the response to be consistent between the front and backend.

These changes enable users to search `/autocomplete/location`  using both the county name and the county fips code. 

**Technical details:**
The response returns a list of counties in the following format:
```json
[
    {"county_fips": "12039", "county_name": "GADSDEN", "state_name": "FLORIDA", "country_name": "UNITED STATES"},
    {"county_fips": "13039", "county_name": "CAMDEN", "state_name": "GEORGIA", "country_name": "UNITED STATES"}
]
```

**Requirements for PR merge:**

1. [x] Unit & integration tests updated
2. [x] API documentation updated
3. [ ] Necessary PR reviewers:
    - [ ] Backend
    - [ ] Frontend <OPTIONAL>
    - [ ] Operations <OPTIONAL>
    - [ ] Domain Expert <OPTIONAL>
5. [ ] Frontend impact assessment completed
6. [ ] Data validation completed
8. [x] Jira Ticket [DEV-11608](https://federal-spending-transparency.atlassian.net/browse/DEV-11608):
    - [x] Link to this Pull-Request

**Area for explaining above N/A when needed:**
```
4. [ ] Matview impact assessment completed
7. [ ] Appropriate Operations ticket(s) created

```

2024-11-08 14:22 UTC, aguest-kc commented
You will need to complete step 7, **Appropriate Operations ticket(s) created**. Since this ticket changes the structure of the Elasticsearch index, it will need to be recreated and repopulated.

We can go over that process together.

2024-11-12 14:30 UTC, aguest-kc submitted a review, later dismissed

2024-11-12 15:46 UTC, anjenkin approved these changes

2024-11-21 20:45 UTC, sethstoudenmier requested changes
One small request change about the regex usage. Open to discussion if there is a reason to not limit the specific character count.

2024-11-21 20:45 UTC, sethstoudenmier commented on usaspending_api/references/v2/views/location_autocomplete.py
> +            counties = [
This seems to work exactly as expected. With all of the nested looped though we should make sure to validate against large QAT dataset before marking the ticket done. Not going to block on this though.

2024-11-22 15:48 UTC, sethstoudenmier approved these changes
Pulled down code and validated that the endpoint works as expected. While I did not personally test further that this works with Databricks, it is my understanding this was tested in Databricks.

2024-11-25 14:44 UTC, merged